# Macaw0S FreeBSD installer defaults
hostname="macaw0s"
root_shell="/bin/sh"
user_name="macaw"
user_shell="/usr/local/bin/zsh"
filesystem="zfs"
zpool_name="zroot"
desktop_session="aviary-shell"
enable_services="dbus seatd sshd zfs ntpd"
