[session]
name=Aviary Shell
compositor=wayfire
launcher=nest-launcher
panel=wing-panel
dock=perch-dock
window_switcher=flight-switcher

[identity]
brand=Macaw0S
visual_language=emerald-graphite-aviary
avoid_platform_clone=true
