[sdl]
fullscreen=false
windowresolution=1280x800
output=opengl

[cpu]
core=auto
cputype=auto
cycles=auto

[dosbox]
machine=svga_s3
memsize=64

[autoexec]
echo Welcome to Macaw0S DOS Compatibility Mode
mount c ~/DOSROOT
c:
