# Macaw0S FreeBSD boot defaults
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
opensolaris_load="YES"
zfs_load="YES"
crypto_load="YES"
aesni_load="YES"
geom_eli_load="YES"
if_bridge_load="YES"
tmpfs_load="YES"
